### ISSUE TITLE
Relax/remove the login timeout

### ISSUE THREAD

**Issue by rorysaur** [simonkernel/kernel-services#21]
Currently the user has 1 minute from loading the login screen (or from clicking "Login with Kernel"?) to finish the login process, which might be a little too strict.

IF we keep the login timeout, then I'll create a separate issue for adding UX/feedback to tell the user that their login process has timed out.

**Comment by simonkernel** [comment]
I pumped it up to 1 day in https://github.com/simonkernel/kernel-services/commit/958c9a994f8f15053829732053b69a7205c44aa6
