### ISSUE TITLE
Save button issue on Unprofile

### ISSUE THREAD

**Issue by glennpoppe** [simonkernel/kernel-services#22]
Wallet: 0xE62CCc8a613618ED5DD87990F8E952e66ABbD835

I filled out the unprofile form on staging (https://staging.unprofile.kernel.community/me) on Brave.  I clicked the "save" button, which turns grey and then returns to green.  It does not advance the page or provide any feedback whether the information has been saved.

**Comment by rorysaur** [comment]
Thanks @glennpoppe! This was on my to-do list as #9 and will be addressed by PR #23.

**Comment by rorysaur** [comment]
This is done.
